### ISSUE TITLE
Requesting a new Rotten Apples folder for Yiddish

### ISSUE THREAD

**Issue by JusGold1** [Venlious/bloob.io-rottenapples#3]
I've created a CAH translation in Yiddish in bloob.io Rotten Apples, and would love to upload it for public use.

**Comment by Venlious** [comment]
Sounds good! Feel free to either make a pull request under a new group "yi-YI" or you can email it to me at contact@bloob.io and I will set everything up for you.

**Comment by Venlious** [comment]
As a quick update, I have added the group you can add the file to. In Bloob.io it may show it as `yi-YI` for now but in a future update this will updated.

https://github.com/Venlious/bloob.io-rottenapples/tree/master/yi-YI

**Comment by JusGold1** [comment]
Thank you! I believe I've successfully proposed a new file, copied in the
contents of the .json and made a pull request - but please let me know if I
haven't quite done it right!

Attaching the .json file here just in case I messed anything up.

-Justin

**Comment by Venlious** [comment]
Hi @JusGold1. I'm afraid I cannot see the pull request or the .json file (I think Github response emails don't include those). If you could email the .json file to contact@bloob.io I'll set everything up for you. Thank you!

**Comment by Venlious** [comment]
Card set has been added! You should now be able to see in-game. I'm not too familiar with the language, but would it be helpful if I add support for making the text align on the right side instead of the left or is it fine as is?

**Comment by JusGold1** [comment]
Thanks, I can see it!

Yes - if there's a way to format the text right-to-left, that would
definitely be helpful, particularly when it comes to punctuation. I'm sorry
I wasn't quite sure how to accomplish that via the web editor!

-j
